AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam_execute_match

  Sample SAM Template for sam_execute_match

  '
Globals:
  Function:
    Timeout: 15
    MemorySize: 256
Resources:
  ExecuteMatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://execute-match/3fa33ba4924caf7134688f7998b85dd0
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        ExecuteMatch:
          Type: Api
          Properties:
            Path: /execute_match
            Method: post
Outputs:
  ExecuteMatchApi:
    Description: API Gateway endpoint URL for Prod stage for Execute Match function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  ExecuteMatchFunction:
    Description: Execute Match Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ExecuteMatchFunction
      - Arn
  ExecuteMathIamRole:
    Description: Implicit IAM Role created for execute match function
    Value:
      Fn::GetAtt:
      - ExecuteMatchFunctionRole
      - Arn
