AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_execute_match

  Sample SAM Template for sam_execute_match

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 256

Resources:
  ExecuteMatchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: execute_match/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        ExecuteMatch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /execute_match
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExecuteMatchApi:
    Description: "API Gateway endpoint URL for Prod stage for Execute Match function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ExecuteMatchFunction:
    Description: "Execute Match Lambda Function ARN"
    Value: !GetAtt ExecuteMatchFunction.Arn
  ExecuteMathIamRole:
    Description: "Implicit IAM Role created for execute match function"
    Value: !GetAtt ExecuteMatchFunctionRole.Arn
